### ISSUE TITLE
Feature: Wrap edit/delete/post/reply actions with authentication check workflow

### ISSUE THREAD

**Issue by kate202212** [katesroad/FeedbackFED#29]
**Background**: The user must have corresponding authentication/permissions before any authentication/permission required operations on the page.

**Direction** :Find an easy-to-use solution to wrap authentication required components 

**Specs from user view**
1. Check authentication status for vote action [**DONE**]
2. Check authentication status for add feedback action on the feedback creation page  [**DONE**]
3. check authentication status for editing feedback action on the feedback editing page [**DONE**]
4. Check authentication status for replying action on replying comment [**DONE**]
5. Check authentication status for adding a new comment on feedback [**DONE**]

**Specs from developer view**:
1. Create RequireAuth component [**DONE** on [PR](https://github.com/katesroad/FeedbackFED/pull/44) ]
2. Check authentication status for user interaction(check specs from user view)

**Comment by katesroad** [comment]
Issue resolved on PR https://github.com/katesroad/FeedbackFED/pull/47
